[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"  # Minimum version required by Vite
  NPM_FLAGS = "--prefix=./"

[dev]
  framework = "qwik"
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"

[[edge_functions]]
  function = "entry.netlify-edge"
  path = "/*"
  
[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
