[build]
  command = "npm run build.server && npm run build.client"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"  # Minimum version required by Vite

[[edge_functions]]
  function = "entry.netlify-edge"
  path = "/*"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
