[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions/"

[build.environment]
  NODE_VERSION = "20.19.0"  # Minimum version required by Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
